blog/urls.py
from django.contrib import admin
from django.urls import path, include
from  blog.views import *
from froala_editor import views

app_name = 'blog'
urlpatterns = [
    path('froala_editor/',include('froala_editor.urls')),
    path('', home, name='home'),
    path('blog/<int:id>/', get_blog, name='get_blog'),
    
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import SET_DEFAULT

from froala_editor.fields import FroalaField

class Category(models.Model):
    category_name = models.CharField(max_length=200, null=True, blank=False)
    
    def __str__(self) -> str:
        return self.category_name
    
class Blog(models.Model):
    title = models.CharField(max_length=200, blank=False)
    banner_image = models.ImageField(upload_to ="blog_banner")
    content = FroalaField()
    category = models.ForeignKey(Category, on_delete = models.SET_DEFAULT, default='Category Removed')#On category delete default category
    user = models.ForeignKey(User, on_delete=models.CASCADE)#On user Delete , delete the blog
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    
    
    
    def __str__(self):
                       
        return self.title

blog/views.py
from django.shortcuts import render
from . models import *

# Create your views here.

def home(request):
    context = {}
    try:
        blogs = Blog.objects.all()
        context['all'] = blogs    
    except Exception as e:
        print(e)
    return render(request, 'blog/home.html', context)
    

def get_blog(request, id):
    context = {}
    try:
        blog_obj = Blog.objects.get(id = id)
        context['blog'] = blog_obj        
    except Exception as e:
        print(e)        
    return render(request, 'blog/blog_details.html', context)

blog/templates/blog/blog_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{blog.title}}</title>
</head>
<body>
    
    <h2>{{blog.title}}</h2>
    
    {{blog.image}}
    {{blog.content|safe}}
    {{blog.user}}
    {{blog.created_at}}
    
</body>
</html>

blog/templates/blog/home.html
{% for blog in all %}
<hr>
{{blog.title}}
{{blog.content|safe}}
<a href="{% url 'blog:get_blog' blog.id %}">view</a>
<hr>
{% endfor %}